test

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -22,5 +22,39 @@ runs:
     - name: Cloning Repository
       shell: bash
       run: |
-        chmod +x ./clone.sh
-        ./clone.sh "${{ inputs.url }}" "${{ inputs.dir }}" "${{ inputs.token }}" "${{ inputs.branch }}"
+        set -e
+        
+        URL="${{ inputs.url }}"
+        DIR="${{ inputs.dir }}"
+        TOKEN="${{ inputs.token }}"
+        BRANCH="${{ inputs.branch }}"
+        
+        if [[ -z "$URL" ]]; then
+          echo "Error: url parameter is required"
+          exit 1
+        fi
+        
+        if [[ -z "$DIR" ]]; then
+          DIR="."
+        fi
+        
+        CLONE_CMD="git clone"
+        
+        if [[ -n "$BRANCH" ]]; then
+          CLONE_CMD="$CLONE_CMD --branch $BRANCH"
+        fi
+        
+        if [[ -n "$TOKEN" ]]; then
+          CLONE_CMD="$CLONE_CMD https://${TOKEN}@${URL}"
+        else
+          CLONE_CMD="$CLONE_CMD $URL"
+        fi
+        
+        CLONE_CMD="$CLONE_CMD $DIR"
+        
+        echo "Cloning repository..."
+        echo "Command: $CLONE_CMD"
+        
+        eval $CLONE_CMD
+        
+        echo "Repository cloned successfully to: $DIR"
